image: maven:latest
# https://docs.gitlab.com/ee/ci/examples/artifactory_and_gitlab/

stages:
  - build
  - deploy
  - release

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -da:org.openrdf..."

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  only:
    - master
  variables:
    PROJECT_VERSION: ${GTC_TEST_VERSION}
  script:
    - echo ${PROJECT_VERSION}
    - mvn $MAVEN_CLI_OPTS -DskipTests=true -Denforcer.skip=true package

deploy:
  stage: deploy
  only:
    - master
  variables:
    PROJECT_VERSION: ${GTC_TEST_VERSION}
  script:
    - echo ${PROJECT_VERSION}
    - mvn $MAVEN_CLI_OPTS -DskipTests=true -Denforcer.skip=true deploy

release:
  stage: release 
  only:
    - master
  variables:
    PROJECT_VERSION: ${GTC_PROD_VERSION}
  script:
    - echo ${PROJECT_VERSION}
    - mvn $MAVEN_CLI_OPTS -DskipTests=true -Denforcer.skip=true deploy
  when: manual
