spring:
    application:
        name: glycosearch
    triplestore:
        driverClassName: virtuoso.jdbc4.Driver
        dialect: sparqs
        url: jdbc:virtuoso://test.ts.glytoucan.org:1111
        #url: jdbc:virtuoso://localhost:1112
        #url: jdbc:virtuoso://glycoinfo:1111
#        url: jdbc:virtuoso://beta.ts.glytoucan.org:1112
        username: dba
   #     password: db@
        password: dba
        graph: graph